USE KUYFREE;
CREATE TABLE IF NOT EXISTS `KUYFREE`.`KYU_ADDRESS_MASTER` (
  `ADDRESS_ID` INT NOT NULL AUTO_INCREMENT,
  `STREET` VARCHAR(255) NOT NULL,
  `STREET1` VARCHAR(255) NULL,
  `CITY` VARCHAR(255) NOT NULL,
  `STATE` VARCHAR(255) NOT NULL DEFAULT 'CA',
  `COUNTRY` VARCHAR(45) NOT NULL DEFAULT 'USA',
  `LATITUDE` VARCHAR(45) NULL,
  `LOGITUDE` VARCHAR(45) NULL,
  `ZIP_CODE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ADDRESS_ID`));


CREATE TABLE IF NOT EXISTS `KUYFREE`.`KYU_PARTNER_MASTER` (
  `PARTNER_ID` INT NOT NULL AUTO_INCREMENT,
  `PARTNER_NAME` VARCHAR(255) NOT NULL,
  `PARTNER_DESCRIPTIO` VARCHAR(2000) NULL DEFAULT 'SHORT DESCRIPTIO',
  `CREATED_ON` DATETIME NOT NULL DEFAULT NOW(),
  `ADDRESS_ID` VARCHAR(400) NOT NULL,
  
  PRIMARY KEY (`PARTNER_ID`, `PARTNER_NAME`));
  
 CREATE TABLE IF NOT EXISTS `KUYFREE`.`KYU_PARTNER_LOCATION` (
  `PARTNER_LOCATION_ID` INT NOT NULL AUTO_INCREMENT,
  `PARTNER_ID` VARCHAR(45) NOT NULL,
  `LOCATION_NAME` VARCHAR(255) NOT NULL,
  `LOCATION_DESC` VARCHAR(500) NOT NULL,
  `ADDRESS_ID` INT NOT NULL  ,
  `CREATED_ON` DATETIME NOT NULL DEFAULT NOW(),
  `MODIFIED_ON` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`PARTNER_LOCATION_ID`));
  
CREATE TABLE IF NOT EXISTS `KUYFREE`.`LOCATION_MENU` (
  `LOCATION_MENU_ID` INT NOT NULL AUTO_INCREMENT,
  `ITEM_NAME` VARCHAR(200) NOT NULL,
  `ITEM_SHOT_DESC` VARCHAR(200) NOT NULL,
  `ITEM_LONG_DESC` VARCHAR(2000) NULL,
  `ITEM_PRICE` DOUBLE NOT NULL,
  `PARTNER_LOCATION_ID` INT NOT NULL,
  `ITEM_IMAGE_NAME` VARCHAR(255) NULL,
  `ACTIVE` VARCHAR(1) NOT NULL DEFAULT 'Y',
  `CREATED_ON` DATETIME NOT NULL DEFAULT NOW(),
  `MODIFIED_ON` DATETIME NOT NULL DEFAULT NOW(),
  `UPDATED_BY` VARCHAR(200) NOT NULL DEFAULT 'SYSTEM',
   `ITEM_TYPE` VARCHAR(1) NOT NULL DEFAULT 'A',
  
  PRIMARY KEY (`LOCATION_MENU_ID`));